version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cosc2430
      MONGO_INITDB_ROOT_PASSWORD: fighting
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cosc2430
      ME_CONFIG_MONGODB_ADMINPASSWORD: fighting
      ME_CONFIG_MONGODB_URL: mongodb://cosc2430:fighting@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: cosc2430
      ME_CONFIG_BASICAUTH_PASSWORD: fighting